# Generated by Django 4.2.1 on 2023-06-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_codingproblem_test_cases_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='test_cases',
        ),
    ]
