version: '3'
services:
  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile.nginx
      ports:
        - "80:80"
      depends_on:
        - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./backend:/code
    depends_on:
      - judge-server
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"

  judge-server:
    build:
      context: ./judge-server
      dockerfile: Dockerfile.judgeservice
    volumes:
      - ./judge-server:/app
    ports:
      - "5000:5000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"