version: "3.7"
services:
  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile.nginx
      ports:
        - "80:80"
      depends_on:
        - backend
        - judge-server
        - frontend
      networks:
        - tukoj_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    command: ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./backend:/code
    depends_on:
      - judge-server
    networks:
      - tukoj_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    networks:
      - tukoj_network

  judge-server:
    build:
      context: ./judge-server
      dockerfile: Dockerfile.judgeservice
    volumes:
      - ./judge-server:/app
    networks:
      - tukoj_network

  redis:
    image: "redis:7.0"
    networks:
      - tukoj_network

networks:
  tukoj_network:
    driver: bridge