# Start from a Python 3.9 base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY ./backend/pyproject.toml /code/
RUN pip install poetry && poetry install

# Copy project
COPY ./backend /code/